// clinic-frontend/src/app/shared/components/sidebar/sidebar.component.ts
import { Component, signal, computed } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterLink, RouterLinkActive } from '@angular/router';
import { AuthService } from '../../../core/services/auth.service';
import {
  LucideAngularModule,
  LayoutDashboard,
  Users,
  Calendar,
  FileText,
  Receipt,
  MessageSquare,
  LogOut,
  Menu,
  X,
  Stethoscope,
  ChevronRight,
  UserCog,
  BarChart2,
} from 'lucide-angular';

@Component({
  selector: 'app-sidebar',
  standalone: true,
  imports: [CommonModule, RouterLink, RouterLinkActive, LucideAngularModule],
  templateUrl: './sidebar.component.html',
})
export class SidebarComponent {
  readonly LayoutDashboard = LayoutDashboard;
  readonly Users = Users;
  readonly Calendar = Calendar;
  readonly FileText = FileText;
  readonly Receipt = Receipt;
  readonly MessageSquare = MessageSquare;
  readonly LogOut = LogOut;
  readonly Menu = Menu;
  readonly X = X;
  readonly Stethoscope = Stethoscope;
  readonly ChevronRight = ChevronRight;
  readonly UserCog = UserCog;

  collapsed = signal(false);

  constructor(public authService: AuthService) {}

  toggle() {
    this.collapsed.update((v) => !v);
  }

  logout() {
    this.authService.logout();
  }

  navItems = [
    {
      label: 'Tableau de bord',
      route: '/dashboard',
      icon: LayoutDashboard,
      roles: ['ADMIN', 'MEDECIN', 'SECRETAIRE'],
    },
    {
      label: 'Patients',
      route: '/patients',
      icon: Users,
      roles: ['ADMIN', 'MEDECIN', 'SECRETAIRE'],
    },
    {
      label: 'Rendez-vous',
      route: '/appointments',
      icon: Calendar,
      roles: ['ADMIN', 'MEDECIN', 'SECRETAIRE'],
    },
    {
      label: 'Prescriptions',
      route: '/prescriptions',
      icon: FileText,
      roles: ['ADMIN', 'MEDECIN'],
    },
    {
      label: 'Facturation',
      route: '/billing',
      icon: Receipt,
      roles: ['ADMIN', 'SECRETAIRE'],
    },
    {
      label: 'Messagerie',
      route: '/messaging',
      icon: MessageSquare,
      roles: ['ADMIN', 'MEDECIN', 'SECRETAIRE'],
    },

    {
      label: 'Statistiques',
      route: '/stats',
      icon: BarChart2,
      roles: ['ADMIN'],
    },
    {
      label: 'Utilisateurs',
      route: '/admin/users',
      icon: UserCog,
      roles: ['ADMIN'],
    },
  ];

  get visibleItems() {
    const role = this.authService.userRole();
    return this.navItems.filter((item) =>
      role ? item.roles.includes(role) : false,
    );
  }
}

<aside
  class="h-screen bg-white border-r border-gray-100 flex flex-col transition-all duration-300 shadow-sm"
  [class.w-64]="!collapsed()"
  [class.w-16]="collapsed()"
>
  <!-- Logo -->
  <div
    class="flex items-center justify-between px-4 h-16 border-b border-gray-100"
  >
    @if (!collapsed()) {
      <div class="flex items-center gap-2.5">
        <div
          class="w-8 h-8 bg-gradient-to-br from-blue-500 to-blue-700 rounded-xl flex items-center justify-center shadow-sm"
        >
          <lucide-icon
            [img]="Stethoscope"
            color="white"
            size="16"
          ></lucide-icon>
        </div>
        <div>
          <span class="font-bold text-gray-900 text-sm">Clinique</span>
          <p class="text-xs text-gray-400 leading-none">Médicale</p>
        </div>
      </div>
    }
    <button
      (click)="toggle()"
      class="p-1.5 rounded-lg hover:bg-gray-100 text-gray-400 hover:text-gray-600 transition-colors"
    >
      <lucide-icon [img]="collapsed() ? Menu : X" size="18"></lucide-icon>
    </button>
  </div>

  <!-- User info -->
  @if (!collapsed()) {
    <div class="mx-3 my-3 p-3 bg-gray-50 rounded-xl">
      <div class="flex items-center gap-3">
        <div
          class="w-9 h-9 bg-gradient-to-br from-blue-500 to-blue-600 rounded-xl flex items-center justify-center shrink-0 shadow-sm"
        >
          <span class="text-white text-xs font-bold">
            {{ authService.userName().charAt(0).toUpperCase() }}
          </span>
        </div>
        <div class="min-w-0">
          <p class="text-sm font-semibold text-gray-900 truncate">
            {{ authService.userName() }}
          </p>
          <span
            class="text-xs px-1.5 py-0.5 rounded-md font-medium"
            [class.bg-blue-100]="authService.userRole() === 'ADMIN'"
            [class.text-blue-700]="authService.userRole() === 'ADMIN'"
            [class.bg-green-100]="authService.userRole() === 'MEDECIN'"
            [class.text-green-700]="authService.userRole() === 'MEDECIN'"
            [class.bg-purple-100]="authService.userRole() === 'SECRETAIRE'"
            [class.text-purple-700]="authService.userRole() === 'SECRETAIRE'"
          >
            {{ authService.userRole() }}
          </span>
        </div>
      </div>
    </div>
  }

  <!-- Nav -->
  <nav class="flex-1 px-3 py-2 space-y-0.5 overflow-y-auto">
    @for (item of visibleItems; track item.route) {
      <a
        [routerLink]="item.route"
        routerLinkActive="bg-blue-50 text-blue-700 font-semibold"
        [routerLinkActiveOptions]="{ exact: item.route === '/dashboard' }"
        class="flex items-center gap-3 px-3 py-2.5 rounded-xl text-gray-600 hover:bg-gray-100 hover:text-gray-900 transition-all duration-150 group"
        [class.justify-center]="collapsed()"
      >
        <lucide-icon
          [img]="item.icon"
          size="18"
          class="shrink-0 transition-transform group-hover:scale-110"
        ></lucide-icon>
        @if (!collapsed()) {
          <span class="text-sm">{{ item.label }}</span>
        }
      </a>
    }
  </nav>

  <!-- Logout -->
  <div class="px-3 py-3 border-t border-gray-100">
    <button
      (click)="logout()"
      class="flex items-center gap-3 px-3 py-2.5 rounded-xl text-red-500 hover:bg-red-50 hover:text-red-600 transition-all duration-150 w-full group"
      [class.justify-center]="collapsed()"
    >
      <lucide-icon
        [img]="LogOut"
        size="18"
        class="shrink-0 group-hover:translate-x-0.5 transition-transform"
      ></lucide-icon>
      @if (!collapsed()) {
        <span class="text-sm font-medium">Déconnexion</span>
      }
    </button>
  </div>
</aside>

// clinique-medicale-front/src/presentation/components/Sidebar.tsx
// src/presentation/components/Sidebar.tsx

import { NavLink } from "react-router-dom";
import { LogOut, Stethoscope } from "lucide-react";
import type { ReactNode } from "react";

export interface SidebarItem {
  to: string;
  label: string;
  icon: ReactNode;
  badge?: number;
}

interface SidebarProps {
  items: SidebarItem[];
  title: string;
  userName: string;
  roleLabel: string;
  onLogout: () => void;
  headerExtra?: ReactNode;
}

export function Sidebar({
  items,
  title,
  userName,
  roleLabel,
  onLogout,
  headerExtra,
}: SidebarProps) {
  return (
    <aside className="flex h-screen w-64 flex-col border-r border-gray-200 bg-white">
      <div className="flex items-center justify-between border-b border-gray-200 px-5 py-4">
        <div className="flex items-center gap-2">
          <div className="flex h-8 w-8 items-center justify-center rounded-md bg-primary-600 text-white">
            <Stethoscope className="h-4 w-4" />
          </div>
          <span className="text-sm font-semibold text-gray-900">{title}</span>
        </div>
        {headerExtra}
      </div>

      <div className="flex items-center gap-3 border-b border-gray-200 px-5 py-4">
        <div className="flex h-8 w-8 items-center justify-center rounded-full bg-primary-100 text-sm font-semibold text-primary-700">
          {userName.charAt(0).toUpperCase()}
        </div>
        <div>
          <p className="text-sm font-medium text-gray-900">{userName}</p>
          <p className="text-xs text-gray-500">{roleLabel}</p>
        </div>
      </div>

      <nav className="flex-1 space-y-1 overflow-y-auto px-3 py-4">
        {items.map((item) => (
          <NavLink
            key={item.to}
            to={item.to}
            className={({ isActive }) =>
              `flex items-center gap-3 rounded-md px-3 py-2 text-sm font-medium transition-colors ${
                isActive
                  ? "bg-primary-50 text-primary-700"
                  : "text-gray-600 hover:bg-gray-100 hover:text-gray-900"
              }`
            }
          >
            {item.icon}
            {item.label}
            {item.badge !== undefined && item.badge > 0 && (
              <span className="ml-auto flex h-5 min-w-[20px] items-center justify-center rounded-full bg-primary-600 px-1.5 text-[11px] font-semibold text-white">
                {item.badge > 9 ? "9+" : item.badge}
              </span>
            )}
          </NavLink>
        ))}
      </nav>

      <div className="border-t border-gray-200 p-3">
        <button
          onClick={onLogout}
          className="flex w-full items-center gap-3 rounded-md px-3 py-2 text-sm font-medium text-danger-600 hover:bg-danger-50"
        >
          <LogOut className="h-4 w-4" />
          Déconnexion
        </button>
      </div>
    </aside>
  );
}
